export const GRID_NEXT_PAGE = "GRID_NEXT_PAGE";
export const GRID_PREV_PAGE = "GRID_PREV_PAGE";
export const SWITCH_GRID_MODE = "SWITCH_GRID_MODE";
export const SWITCH_LIST_MODE = "SWITCH_LIST_MODE";
export const UPDATE_SUBS = "UPDATE_SUBS";
export const SET_LIST_LAST_PAGE = "SET_LIST_LAST_PAGE";
export const AUTO_NEXT_PAGE = "AUTO_NEXT_PAGE";

export const SET_ARTICLE_INDEX = "SET_ARTICLE_INDEX";
export const PUSH_SUBS = "PUSH_SUBS";
export const POP_SUBS = "POP_SUBS";
export const LIST_PREV_PAGE = "LIST_PREV_PAGE";
export const LIST_NEXT_PAGE = "LIST_NEXT_PAGE";
export const UPDATE_NEWS = "UPDATE_NEWS";

export const SWITCH_GRID_TOTAL = "SWITCH_GRID_TOTAL";
export const SWITCH_GRID_SUBS = "SWITCH_GRID_SUBS";
export const SWITCH_LIST_TOTAL = "SWITCH_LIST_TOTAL";
export const SWITCH_LIST_SUBS = "SWITCH_LIST_SUBS";
