export const GO_NEXT_PAGE = "GO_NEXT_PAGE";
export const GO_PREV_PAGE = "GO_PREV_PAGE";
export const SWITCH_GRID_MODE = "SWITCH_GRID_MODE";
export const SWITCH_LIST_MODE = "SWITCH_LIST_MODE";
export const UPDATE_SUBS = "UPDATE_SUBS";
export const SET_LIST_LAST_PAGE = "SET_LIST_LAST_PAGE";
export const AUTO_NEXT_PAGE = "AUTO_NEXT_PAGE";
export const RESET_ARTICLE_INDEX = "RESET_ARTICLE_INDEX";
